fetch('https://akabab.github.io/superhero-api/api/id/100.json')
.then(response => response.json())
.then (data => {
if(data.powerstats.intelligence > 90)
console.log ("intelligence > 90")
if(data.powerstats.power > 90)
console.log ("power > 90")
if(data.powerstats.durability > 90)
console.log ("durability > 90")
if(data.powerstats.speed > 90)
console.log ("speed > 90")
if(data.powerstats.combat > 90)
console.log ("combat > 90")
if(data.powerstats.strength > 90)
console.log ("strength > 90")
})
